baseURL = 'https://tianboqiu.com/'
languageCode = 'en-us'
title = 'Tianbo'

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^VERCEL$']

[params]
  name = '邱天博 (Tianbo Qiu)'
  tags = '古法编程 | decaf | Go 学习中'
  github = 'https://github.com/Tianbo-Qiu'
  email = 'tianboqiu@gmail.com'
